//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by validation-gen. DO NOT EDIT.

package pattern

import (
	context "context"
	fmt "fmt"
	regexp "regexp"

	operation "k8s.io/apimachinery/pkg/api/operation"
	safe "k8s.io/apimachinery/pkg/api/safe"
	validate "k8s.io/apimachinery/pkg/api/validate"
	field "k8s.io/apimachinery/pkg/util/validation/field"
	testscheme "k8s.io/code-generator/cmd/validation-gen/testscheme"
)

func init() { localSchemeBuilder.Register(RegisterValidations) }

// RegisterValidations adds validation functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterValidations(scheme *testscheme.Scheme) error {
	// type Struct
	scheme.AddValidationFunc((*Struct)(nil), func(ctx context.Context, op operation.Operation, obj, oldObj interface{}) field.ErrorList {
		switch op.Request.SubresourcePath() {
		case "/":
			return Validate_Struct(ctx, op, nil /* fldPath */, obj.(*Struct), safe.Cast[*Struct](oldObj))
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresource: %v", obj, op.Request.SubresourcePath()))}
	})
	return nil
}

var patternFor_k8s_io_code_generator_cmd_validation_gen_output_tests_tags_pattern_PatternType = regexp.MustCompile("^[a-z]+$")

// Validate_PatternType validates an instance of PatternType according
// to declarative validation rules in the API schema.
func Validate_PatternType(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *PatternType) (errs field.ErrorList) {
	errs = append(errs, validate.Pattern(ctx, op, fldPath, obj, oldObj, patternFor_k8s_io_code_generator_cmd_validation_gen_output_tests_tags_pattern_PatternType)...)

	return errs
}

var patternFor_k8s_io_code_generator_cmd_validation_gen_output_tests_tags_pattern_Struct_patternField = regexp.MustCompile("^[a-z]+$")
var patternFor_k8s_io_code_generator_cmd_validation_gen_output_tests_tags_pattern_Struct_patternPtrField = regexp.MustCompile("^[a-z]+$")
var patternFor_k8s_io_code_generator_cmd_validation_gen_output_tests_tags_pattern_Struct_patternUnvalidatedTypedefField = regexp.MustCompile("^[a-z]+$")
var patternFor_k8s_io_code_generator_cmd_validation_gen_output_tests_tags_pattern_Struct_patternUnvalidatedTypedefPtrField = regexp.MustCompile("^[a-z]+$")

// Validate_Struct validates an instance of Struct according
// to declarative validation rules in the API schema.
func Validate_Struct(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *Struct) (errs field.ErrorList) {
	// field Struct.TypeMeta has no validation

	// field Struct.PatternField
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *string, oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil
			}
			// call field-attached validations
			errs = append(errs, validate.Pattern(ctx, op, fldPath, obj, oldObj, patternFor_k8s_io_code_generator_cmd_validation_gen_output_tests_tags_pattern_Struct_patternField)...)
			return
		}(fldPath.Child("patternField"), &obj.PatternField, safe.Field(oldObj, func(oldObj *Struct) *string { return &oldObj.PatternField }), oldObj != nil)...)

	// field Struct.PatternPtrField
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *string, oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil
			}
			// call field-attached validations
			errs = append(errs, validate.Pattern(ctx, op, fldPath, obj, oldObj, patternFor_k8s_io_code_generator_cmd_validation_gen_output_tests_tags_pattern_Struct_patternPtrField)...)
			return
		}(fldPath.Child("patternPtrField"), obj.PatternPtrField, safe.Field(oldObj, func(oldObj *Struct) *string { return oldObj.PatternPtrField }), oldObj != nil)...)

	// field Struct.PatternUnvalidatedTypedefField
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *UnvalidatedStringType, oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil
			}
			// call field-attached validations
			errs = append(errs, validate.Pattern(ctx, op, fldPath, obj, oldObj, patternFor_k8s_io_code_generator_cmd_validation_gen_output_tests_tags_pattern_Struct_patternUnvalidatedTypedefField)...)
			return
		}(fldPath.Child("patternUnvalidatedTypedefField"), &obj.PatternUnvalidatedTypedefField, safe.Field(oldObj, func(oldObj *Struct) *UnvalidatedStringType { return &oldObj.PatternUnvalidatedTypedefField }), oldObj != nil)...)

	// field Struct.PatternUnvalidatedTypedefPtrField
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *UnvalidatedStringType, oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil
			}
			// call field-attached validations
			errs = append(errs, validate.Pattern(ctx, op, fldPath, obj, oldObj, patternFor_k8s_io_code_generator_cmd_validation_gen_output_tests_tags_pattern_Struct_patternUnvalidatedTypedefPtrField)...)
			return
		}(fldPath.Child("patternUnvalidatedTypedefPtrField"), obj.PatternUnvalidatedTypedefPtrField, safe.Field(oldObj, func(oldObj *Struct) *UnvalidatedStringType { return oldObj.PatternUnvalidatedTypedefPtrField }), oldObj != nil)...)

	// field Struct.PatternValidatedTypedefField
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *PatternType, oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil
			}
			// call the type's validation function
			errs = append(errs, Validate_PatternType(ctx, op, fldPath, obj, oldObj)...)
			return
		}(fldPath.Child("patternValidatedTypedefField"), &obj.PatternValidatedTypedefField, safe.Field(oldObj, func(oldObj *Struct) *PatternType { return &oldObj.PatternValidatedTypedefField }), oldObj != nil)...)

	// field Struct.PatternValidatedTypedefPtrField
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *PatternType, oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil
			}
			// call the type's validation function
			errs = append(errs, Validate_PatternType(ctx, op, fldPath, obj, oldObj)...)
			return
		}(fldPath.Child("patternValidatedTypedefPtrField"), obj.PatternValidatedTypedefPtrField, safe.Field(oldObj, func(oldObj *Struct) *PatternType { return oldObj.PatternValidatedTypedefPtrField }), oldObj != nil)...)

	return errs
}
